TrishaAmman/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from mygoddess import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('goddess_temple/',views.goddess_temple,name='goddess_temple'),
    path('seva_edit/',views.editseva,name='seva_edit'),
    path('seva_delete/',views.deleteseva,name='seva_delete'),
    path('devotees/',views.devotees,name='devotees'),
    path('nayanathara_devotee/',views.nayanathara_devotee,name='nayanathara'),
    path('kajal_devotee/',views.kajal_devotee,name='kajal'),
    path('anushka_devotee/',views.anushka_devotee,name='anushka'),
    path('slaves/',views.slaves,name='slaves'),
    path('signup/',views.signup,name='signup'),
    path('add_profile/',views.user_add_profile,name='add_profile'),
    path('profile_detail/<int:id>/',views.profile_detail,name='profile_detail'),
    path('slaves_pics/<int:id>/',views.goddess_trisha_slaves,name='slave_pics'),
    path('accounts/login/',views.user_login,name='login'),
    path('accounts/logout/',views.user_logout,name='logout'),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mygoddess/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    slave = models.ForeignKey(User,on_delete=models.CASCADE)
    gender = models.CharField(max_length=100)
    image = models.ImageField(upload_to="slaves_pics",blank=True,null=True)
    experience = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.slave)

class TrishaSlave(models.Model):
    name = models.ForeignKey(Profile,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='trisha_slaves')
    description = models.CharField(max_length=500,default="GoddessTrisha Slave")
    
    def __str__(self):
        return str(self.name)+"@"+str(self.image)


class Devotees(models.Model):
    name = models.CharField(max_length=500)
    picture = models.ImageField(upload_to = 'devotee_pics',default="Picture")
    religion = models.CharField(max_length=100)
    story = models.TextField(default="భగవాన్ త్రిషకృష్ణన్ దేవత భక్తుడిని అయినందుకు నేను గర్విస్తున్నాను")

    def __str__(self):
        return self.name

class Seva(models.Model):
    devotee = models.ForeignKey(Devotees,related_name='devotees',on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    date = models.DateField()

    def __str__(self):
        return self.name

mygoddess/forms.py
from django import forms
from mygoddess.models import *
from django.contrib.admin.widgets import AdminDateWidget

RELIGION_CHOICES = [
    ('trishaism', 'Trishaism'),
]

gen = [('male','Male'),('female','Female')]

class DevoteesForm(forms.ModelForm):
    religion = forms.ChoiceField(choices=RELIGION_CHOICES)
    class Meta:
        model = Devotees
        fields = ['name', 'religion','picture','story']

class DateInput(forms.DateInput):
    input_type = 'date'

class SevaForm(forms.ModelForm):
    date = forms.DateField(widget=DateInput)
    class Meta:
        model = Seva
        fields = ['devotee', 'name', 'date']

class ProfileForm(forms.ModelForm):
    gender =forms.ChoiceField(choices=gen,widget=forms.RadioSelect())
    class Meta:
        model = Profile
        fields = ['image','gender','experience']
    
class TrishaSlaveForm(forms.ModelForm):
    class Meta:
        model = TrishaSlave
        fields = ['image','description']
   
  

mygoddess/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from mygoddess.models import *
from mygoddess.forms import *
from django.core.files.storage import default_storage
import os
import random
import shutil
# Create your views here.
def is_login(request):
    try:
        if request.user.id:
            return True
    except Exception as e:
        print(e)
    return False

def home(request):
    users = User.objects.all()
    return render(request,'mygoddess/index.html',context={'users':users})

@login_required
def nayanathara_devotee(request):
    users = User.objects.all()
    return render(request,'mygoddess/nayanathara_devotee.html',context={'users':users})

def kajal_devotee(request):
    users = User.objects.all()
    return render(request,'mygoddess/kajal_devotee.html',context={'users':users})

def anushka_devotee(request):
    users = User.objects.all()
    return render(request,'mygoddess/anushka_devotee.html',context={'users':users})

def signup(request):
    if is_login(request):
        return redirect("home")
    if request.method=="POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        username = request.POST.get('username')
        password = request.POST.get('password')
        re_password = request.POST.get('re_password')
        check =request.POST.get('check')
        try:
            index = email.find("@")
        except:
            pass
        if check ==  'True':
            if len(name) == 0:
                messages.error(request, 'Please Enter Name')
            elif len(email) == 0:
                messages.error(request, 'Please Enter Email')
            elif len(username)==0:
                messages.error(request, 'Please Enter Username')
            elif len(password)==0:
                messages.error(request, 'Please Enter Password')
            elif len(re_password)==0:
                messages.error(request, 'Please Confirm Password')
            elif password != re_password:
                messages.error(request, 'Password did not match!')
            elif User.objects.filter(email=email).exists():
                messages.error(request, 'Email Already Exists')
            elif email[index+1:] != "trishadevotee.com":
                messages.error(request, 'Your Email must be end with trishadevotee.com')
            elif User.objects.filter(username=username).exists():
                messages.error(request, 'Username Already Exists')
            else:
                user = User.objects.create_user(first_name=name, username=username, email=email, password=password)
                if user.is_active:
                    print("register")
                    login(request,user)
                    messages.success(request, "మీరు అదృష్టవంతులు కావున త్రిషా అమ్మవారికి భక్తులయ్యారు")
                else:
                    print("error")
                    messages.error(request, "Please Enter Correct Details!")
        else:
            messages.error(request,"Sorry! You should be Live as a GoddessTrisha Devotee,So Please Check The Box.")
        context={'name':name,'email':email,'username':username,'password':password,'re_password':re_password}
        return render(request, 'mygoddess/signup.html',context)
    users = User.objects.all()
    return render(request, 'mygoddess/signup.html',{'users':users})

@login_required
def user_add_profile(request):
    if request.method == "POST":
        profile_form = ProfileForm(request.POST,request.FILES)
        if profile_form.is_valid():
            profile_form.cleaned_data['slave'] = request.user
            profile = Profile(**profile_form.cleaned_data)
            if Profile.objects.filter(slave = request.user).exists():
                return JsonResponse({"status":"మీరు ఇదివరకు పూర్వమే త్రిషాదేవి పాదదాసులయ్యారు!"})
            else:
                profile.save()
                return JsonResponse({"status":"అభినందనలు మీరు పూర్తిగా త్రిషాదేవి పాదదాసులయ్యారు!"})
        else:
            return JsonResponse({"status":"దయచేసి అన్నీ వివరాలు సరిగ్గా నమోదు చేయండి!"})
    else:
        profile_form = ProfileForm()
    users = User.objects.all()
    context = {'profile_form':profile_form,'users':users}
    return render(request,'mygoddess/add_profile.html',context)

@login_required
def profile_detail(request,id):
    profile = Profile.objects.get(slave = User.objects.get(id=id))
    users = User.objects.all()
    if request.method == "POST":
        trisha_slave_form = TrishaSlaveForm(request.POST,request.FILES)
        if trisha_slave_form.is_valid():
            picture = i = str("_".join(str(trisha_slave_form.cleaned_data['image']).split()))
            if default_storage.exists(os.path.join(str(os.getcwd()),'media\\trisha_slaves',picture)):
                return JsonResponse({"status":"Image Already Exists!"})
            elif default_storage.exists(os.path.join(str(os.getcwd()),'media\\trisha_slaves',str(trisha_slave_form.cleaned_data['image']))):
                return JsonResponse({"status":"Image Already Exists!"})
            else:
                trisha_slave_form.cleaned_data['name'] = profile
                trisha_slave = TrishaSlave(**trisha_slave_form.cleaned_data)
                trisha_slave.save()
                return JsonResponse({"status":"Uploaded Successfully!"})
        else:
            return JsonResponse({"status":"Error while uploading!"})
    else:
        trisha_slave_form  = TrishaSlaveForm()
    context = {'users':users,'profile':profile,'trisha_slave_form':trisha_slave_form}
    return render(request,'mygoddess/profile_detail.html',context)

@login_required
def goddess_trisha_slaves(request,id):
    try:
        slave_img = TrishaSlave.objects.filter(name = Profile.objects.get(id=id))
    except:
        return HttpResponse("No Profiles Found!")
    users = User.objects.all()
    return render(request,'mygoddess/slave_pics.html',context={'users':users,'slave_pics':slave_img})


def user_login(request):
    if is_login(request):
        return redirect("home")
    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username,password=password)
        if user:
            login(request,user)
            return JsonResponse({"status":"Login Successful!"})
        else:
            if len(username) == 0:
                return JsonResponse({'status':'Enter Username'})
            elif len(password) == 0:
                return JsonResponse({'status':'Enter Password'})
            else:
                return JsonResponse({'status':'Invalid Credentials'})
    users = User.objects.all()
    return render(request, 'mygoddess/login.html',context={'users':users})

@login_required
def user_logout(request):
    logout(request)
    return redirect('home')

@login_required
def devotees(request):
    if request.method == "POST":
        name = request.POST.get('name')
        form = DevoteesForm(request.POST,request.FILES)
        if Devotees.objects.filter(name = name).exists():
            messages.error(request, "Devotee Already Exists!")
        elif form.is_valid():
            form.save()
            messages.success(request,"Congrats You Became GoddessTrisha Devotee!")
        else:
            messages.error(request, "Congrats You Became GoddessTrisha Devotee!")
    else:
        form = DevoteesForm()
    users = User.objects.all()
    return render(request, 'mygoddess/devotees.html', context={'form': form,'users':users})

@login_required
def goddess_temple(request):
    if request.method=="POST":
        devotee = request.POST.get('devotee')
        name = request.POST.get('name')
        date = request.POST.get('date')
        form = SevaForm(request.POST)
        if Seva.objects.filter(Q(devotee = devotee)&Q(date=date)).exists():
            return JsonResponse({"status": "Devotee Already Booked a Slot on this date!"})
        if form.is_valid():
            form.save()
            sevas = Seva.objects.values()
            seva_edit = list(sevas)
            return JsonResponse({"status": "1","status_message":"Slot Booked for Serving  Goddess Trisha!","sevas":seva_edit})
        else:
            return JsonResponse({'status_message': 'Failed to Book a Slot'})
    else:
        form = SevaForm()
    sevas = Seva.objects.all()
    users = User.objects.all()
    return render(request,'mygoddess/goddess_temple.html',context={'form':form,'sevas':sevas,'users':users})

@login_required
def editseva(request):
    edit_id = request.POST.get('edit_id')
    devotee =request.POST.get('devotee')
    name = request.POST.get('name')
    date = request.POST.get('date')
    Seva.objects.filter(id=edit_id).update(devotee=devotee,name=name,date=date)
    sevas = Seva.objects.values()
    seva_edit = list(sevas)
    return JsonResponse({"status": "1","status_message":"Seva Updated Successfully!", "sevas": seva_edit})

@login_required
def deleteseva(request):
    delete_id=request.GET.get("delete_id")
    print(delete_id)
    Seva.objects.filter(id=delete_id).first().delete()
    sevas=Seva.objects.values()
    seva_edit=list(sevas)
    return JsonResponse({"status":"1","status_message":"Seva Deleted Successfully!","sevas":seva_edit})

@login_required
def slaves(request):
    users = User.objects.all()
    return render(request,'mygoddess/slaves.html',context={'users':users})

templates/mygoddess/anushka_devotee.html
{% extends 'mygoddess/base.html' %}
{% load static %}
{% block title %}Trisha Amman Temple {% endblock %}
{% block content %}
<div class="text-success alert" style="background-image:url('http://127.0.0.1:8000/static/background_images/devi.jpg')">
    <div class="row">

            <img src="{% static 'Devotional/goddess_trishakrishnan.png' %}" width="100%">

        </div>
    <div class="row text-primary" style="border-style:groove;background-image:url('http://127.0.0.1:8000/static/background_images/god_01.jpg')">

        </div>

    </div>

</div>
{% endblock %}

templates/mygoddess/devotees.html
{% extends 'mygoddess/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Trisha Amman Temple {% endblock %}
{% block content %}
<div class="text-danger alert" style="background-image: url('http://127.0.0.1:8000/static/background_images/god_01.jpg');">
    <div class="row">
        <div class="col-md-8 table-responsive rounded border" style="background-image: url('http://127.0.0.1:8000/static/background_images/trisha34.jpg');">
             <ul class="messages">
    {% for message in messages %}
    <li id="error_text" {% if message.tags %} class="bg-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
              <h3 clss="p-2">Register Yourself as Goddess TrishaDevotees</h3>
            <form method="POST" enctype="multipart/form-data" id="devoteeForm">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" class="btn btn-success mt-2" value="Register">
            </form>
        </div>
    </div>
    <div class="row mt-3">
<div class="col-md-4">
                <video id="trisha1" style="border-style:groove;" controls="" loop=""  muted="" autoplay="" width=100%>
                    <source src="{% static 'videos/GodTrishaqueen.mp4' %}" type="video/mp4">
                    </video>
                <video style="margin-top:80px;border-style:groove;" id="trisha2" controls="" loop=""  muted="" autoplay="" width=100%>
                    <source src="{% static 'videos/devadevi.mp4' %}" type="video/mp4">
                    </video>
            </div>
<div class="col-md-4">
                <video id="trisha3" style="border-style:groove;" controls="" loop=""  muted="" autoplay="" width=100%>
                    <source src="{% static 'videos/TrishaPadam.mp4' %}" type="video/mp4">
                    </video>
                <video style="margin-top:80px;border-style:groove;" id="trisha4" controls="" loop=""  muted="" autoplay="" width=100%>
                    <source src="{% static 'videos/Trishadevi.mp4' %}" type="video/mp4">
                    </video>
            </div>
<div class="col-md-4">
                <video id="trisha5" style="border-style:groove;" controls="" loop=""  muted="" autoplay=""  width=100%>
                    <source src="{% static 'videos/GoddessTrishaWalk.mp4' %}" type="video/mp4">
                    </video>

            </div>
    </div>
<div class="row mt-3">
    <div class="col-md-6">
        <video id="trisha6" style="border-style:groove;height:300px;" controls="" loop=""  muted="" autoplay=""  width=100%>
                    <source src="{% static 'videos/GoddessTrisha.mp4' %}" type="video/mp4">
                    </video>
    </div>
    <div class="col-md-6">
        <video id="trisha7" style="border-style:groove;height:300px;" controls="" loop=""  muted="" autoplay=""  width=100%>
                    <source src="{% static 'videos/TrishaBhagawathi.mp4' %}" type="video/mp4">
                    </video>
    </div>
</div>
    </div>
</div>
<!--<script-->
<!--  src="https://code.jquery.com/jquery-3.6.0.js"-->
<!--  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="-->
<!--  crossorigin="anonymous"></script>-->
<!--<script type="text/javascript">-->
<!--$(document).on("submit","#devoteeForm",function(e){-->
<!--e.preventDefault();-->
<!--var name = $("#id_name").val();-->
<!--var religion =$("#id_religion").val()-->
<!--var picture = $("#id_picture").src-->
<!--var story = $("#id_story").val()-->
<!--$.ajax({-->
<!--type:"POST",-->
<!--url:"{% url 'devotees' %}",-->
<!--data:{-->
<!--'name':name,-->
<!--'religion':religion,-->
<!--'picture':picture,-->
<!--'story':story,-->
<!--csrfmiddlewaretoken:$("input[name=csrfmiddlewaretoken]").val()-->
<!--},-->
<!--success:function(response){-->
<!--console.log(response)-->
<!--}-->
<!--})-->
<!--})-->
<!--</script>-->
{% endblock %}

templates/mygoddess/goddess_temple.html
{% extends 'mygoddess/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}Trisha Amman Temple {% endblock %}
{% block content %}
  <link rel="stylesheet" href="//cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css">
<div class="text-primary alert" style="background-image: url('http://127.0.0.1:8000/static/background_images/trisha15.jpg');">
    <div class="row">
        <div class="col-md-4 table-responsive rounded border" style="background-image: url('http://127.0.0.1:8000/static/background_images/goddess_10.jpg');">
            <p id="message"></p>
            <h3 clss="p-2">Book Yourself for Serving Goddess TrishaDevi</h3>
            <form method="POST" enctype="multipart/form-data" id="goddessForm">
                {% csrf_token %}
                {{form|crispy}}
                <input type="submit" id="book" class="btn btn-success mt-2" value="Book">
            </form>
            <p>Register As Devotee <a href="{% url 'devotees' %}">Devotee</a></p>
        </div>
        <div class="col-md-8 table-responsive text-success" style="background-image: url('http://127.0.0.1:8000/static/background_images/god_01.jpg');border-style:groove;">
            <table id="myTable" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th scope="col">S.no</th>
                <th scope="col">Devotee</th>
                <th scope="col">Devotee Image</th>
                <th scope="col">Seva</th>
                <th scope="col">Date</th>
                <th scope="col">Edit</th>
                <th scope="col">Delete</th>
            </tr>
        </thead>
        <tbody>
        {% for seva in sevas %}
            <tr>
               <th scope="row">{{forloop.counter}}</th>
                <td class="devotee">{{seva.devotee}}</td>
                <td><img src="{{seva.devotee.picture.url}}" height="80px"></td>
                <td class="name">{{seva.name}}</td>
                <td class="date">{{seva.date}}</td>
                <td><button class="btn btn-secondary edit" data="{{seva.id}}">Edit</button></td>
              <td><button class="btn btn-danger delete" data="{{seva.id}}">Delete</button></td>

            </tr>
        {% endfor %}
    </table>
        </div>
    </div>
</div>
  <script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
  <script src="//cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
<script>
 $(document).ready( function () {
    $("#myTable").DataTable();
} );

function showSevas(data){
 $("#myTable tbody").empty()
  for(i=0;i<data.length;i++){
  $("#myTable tbody").append(
    `
    <tr>
  <th scope="row">${i+1}</th>
  <td class="devotee">${data[i].devotee_id}</td>
  <td class="name">${data[i].name}</td>
  <td class="date">${data[i].date}</td>
  <td><button class="btn btn-secondary edit" data="${data[i].id}">Edit</button></td>
  <td><button class="btn btn-danger delete" data="${data[i].id}">Delete</button></td>
 </tr>
    `
  )
}
}



let activeItem=null;
function editItem(item){
var devotee = item.find(".devotee").text()
var name = item.find(".name").text()
var date = item.find(".date").text()
var edit_id = item.find('.edit').attr("data")
console.log(devotee,name,date,edit_id)
$("#id_devotee").val(devotee)
$("#id_name").val(name)
$("#id_date").val(date)
$("#book").val("Update")
$("#book").removeClass("bg-success")
$("#book").addClass("bg-warning")
activeItem = edit_id
}

function deleteSeva(delete_id){
  var con=confirm("Are You Sure Want To Delete?")
  if(con==true){

    $.ajax({
    type:"GET",
    url:"{% url 'seva_delete' %}",
    data:{
      'delete_id':delete_id
    },
    success:function(response){
      console.log(response.sevas)
      showSevas(response.sevas)

      if(response.status_message=="Seva Deleted Successfully!"){
        $("#message").text(response.status_message)
              $("#message").removeClass("bg-success")
              $("#message").removeClass("bg-warning")
              $("#message").addClass("bg-danger")
      }
        $(".delete").click(function(){
              var delete_id=$(this).attr("data")
              console.log(delete_id)
              deleteSeva(delete_id)
            })
        $(".edit").click(function(){
            var item=$(this).attr("data")
            editItem(item)
            })
    }
  })

  }

}





$(document).on("submit","#goddessForm",function(e){
e.preventDefault();
var devotee = $("#id_devotee").val();
var name =$("#id_name").val()
var date = $("#id_date").val()
var url = "{% url 'goddess_temple' %}";
var data = {
'devotee':devotee,
'name': name,
'date':date,
csrfmiddlewaretoken:$("input[name=csrfmiddlewaretoken]").val()
};

 if(activeItem != null){
      url="{% url 'seva_edit' %}"
      data['edit_id']=activeItem
      console.log(url)
    }

$.ajax({
type:"POST",
url:url,
data:data,
success:function(response){
console.log(response.status)
data = response.sevas
$("#message").addClass("p-2")
$("#message").text(response.status_message)
console.log(data)
if(response.status == "1"){
showSevas(data)
$("#message").removeClass("bg-danger")
$("#message").removeClass("bg-warning")
$("#message").addClass("bg-success")
}else{
$("#message").removeClass("bg-success")
$("#message").removeClass("bg-warning")
$("#message").addClass("bg-danger")
}

$('.edit').click(function(){
var item = $(this).closest('tr')
editItem(item)
})
$('.delete').click(function(){
var delete_id= $(this).attr("data")
deleteSeva(delete_id)
})

if(response.status_message=="Seva Updated Successfully!"){
              $("#message").text(response.status_message)
              $("#message").removeClass("bg-success")
              $("#message").removeClass("bg-danger")
              $("#message").addClass("bg-warning")
              $("#book").val('Book')
              $("#book").removeClass("bg-warning")
              $("#book").addClass("bg-success")
              activeItem=null
            }


}
})
})
$('.edit').click(function(){
var item = $(this).closest('tr')
editItem(item)
})
$('.delete').click(function(){
var delete_id = $(this).attr("data")
deleteSeva(delete_id)
})
</script>
{% endblock %}

templates/mygoddess/kajal_devotee.html
{% extends 'mygoddess/base.html' %}
{% load static %}
{% block title %}Trisha Amman Temple {% endblock %}
{% block content %}
<div class="text-success alert" style="background-image:url('http://127.0.0.1:8000/static/background_images/god_500.jpg')">
    <div class="row">

            <img src="{% static 'Devotional/goddess_amman.png' %}" width="100%">

        </div>
    <div class="row text-primary" style="border-style:groove;background-image:url('http://127.0.0.1:8000/static/background_images/god_01.jpg')">

        </div>

    </div>

</div>
{% endblock %}

templates/mygoddess/signup.html
{% extends 'mygoddess/base.html' %}
{% load static %}
{% block title %}Trisha Amman Temple {% endblock %}
{% block content %}
<div class="text-white alert" style="color:white;background-image: url('http://127.0.0.1:8000/static/background_images/trisha300.jpg')">
    <h4>త్రిషా అమ్మవారికి భక్తుడయ్యే అదృష్టాన్ని పొందండి</h4>
    <div class="border col-md-4 table-responsive" style="background-image: url('http://127.0.0.1:8000/static/background_images/devi.jpg')">
        {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li id="error_text" {% if message.tags %} class="bg-{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
        <p class="text-white" id="message"></p>
        <h3 class="p-3">Became a GoddessTrisha Amman Devoteee</h3>
        <form method="POST" id="signupForm" enctype="multipart/form-data">
            {% csrf_token %}
            <table class="table" style="color:white;font-style:bold;">
                <tr>
                    <td>Name</td>
                    <td><input type="post" name="name" id="id_name" placeholder="Enter Name" value="{{name}}"> </td>
                </tr>
                <tr>
                    <td>Email</td>
                    <td><input type="email" name="email" id="id_email" placeholder="@trishadevotee.com" value="{{email}}"> </td>
                </tr>
                <tr>
                    <td>Username</td>
                    <td><input type="post" name="username" id="id_username" placeholder="Enter Username" value="{{username}}"> </td>
                </tr>
                <tr>
                    <td>Password</td>
                    <td><input type="password" name="password" id="id_password" placeholder="Enter Password" value="{{password}}"> </td>
                </tr>
                <tr>
                    <td>ConfirmPassword</td>
                    <td><input type="post" name="re_password" id="id_re_password" placeholder="ReEnter Password" value="{{re_password}}"> </td>
                </tr>
                <tr>
                    <td style="color:blue;font-size:20;font-style:bold;">Do You Want to Live as a Devotee of GoddessTrisha Amman?</td>
                    <td><input type="checkbox" name="check" value="t"  id="id_checkbox"></td>
                </tr>
                <tr>
                    <td><input type="submit" class="btn btn-success" value="Signup"></td>
                </tr>
            </table>
        </form>
    </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.6.0.js"
  integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
  crossorigin="anonymous"></script>
<script>
  function Check(id) {
        var chkPassport = document.getElementById(id);
        if (chkPassport.checked) {
                return "True"
        } else {

                return "False"
        }
    }
    $(document).on('submit','#signupForm',function(e){
    e.preventDefault();
    var name = $("#id_name").val()
    var email = $("#id_email").val()
    var username = $("#id_username").val()
    var password = $("#id_password").val()
    var re_password = $("#id_re_password").val()
    var check = Check("id_checkbox")
    $.ajax({
    type:"POST",
    url:"{% url 'signup' %}",
    data:{'name':name,'email':email,'username':username,
    'password':password,'re_password':re_password,'check':check,
    csrfmiddlewaretoken:$("input[name=csrfmiddlewaretoken]").val()
    },
    success:function(response){
    console.log(check)
    var message = $(response).find("#error_text")
    var message_class =  message.attr("class")
    console.log(message.text())
    $("#message").text(message.text())
    $("#message").addClass("p-2")
    if (message.text() == "మీరు అదృష్టవంతులు కావున త్రిషా అమ్మవారికి భక్తులయ్యారు"){
        $("#message").removeClass("bg-danger")
        $("#message").addClass("bg-success")
        window.location = "{% url 'add_profile' %}"
    }else{
        $("#message").removeClass("bg-success")
        $("#message").addClass("bg-danger")
    }
    
    }
    })
    })
</script>
{% endblock %}